basePath: /api/v1
definitions:
  Response:
    properties:
      code:
        description: |-
          Code is the status code by default, but also can be
          a custom code
        type: integer
      data:
        description: Data accepts any thing as the response data
      message:
        description: Message shows detail thing back to caller
        type: string
      request_id:
        description: RequestID needs to be used with middleware
        type: string
    type: object
  models.Data:
    properties:
      app_id:
        type: string
      attributes:
        additionalProperties:
          $ref: '#/definitions/models.types'
        type: object
      browser_language:
        type: string
      event:
        type: string
      event_type:
        type: string
      message_id:
        type: string
      page_title:
        type: string
      page_url:
        type: string
      screen_size:
        type: string
      traits:
        additionalProperties:
          $ref: '#/definitions/models.types'
        type: object
      user_id:
        type: string
    type: object
  models.types:
    properties:
      type:
        type: string
      value:
        type: string
    type: object
info:
  contact:
    email: venkateshwarachinnasamy@gmail.com
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: webhook API
  version: "1.0"
paths:
  /uplink:
    post:
      consumes:
      - application/json
      description: send data
      operationId: payload
      parameters:
      - description: body parameter
        in: body
        name: body
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Data'
        "404":
          description: 'bad request: validate your input params'
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: Payload
      tags:
      - payload
swagger: "2.0"
